### PR TITLE
OBO fix

### PR DESCRIPTION
**Pull request by matentzn**
- wbbt.obo now is a simple release containing only terms from the wbbt namespace
- there is a new artefact type wbbt-simple.obo

### CODE REVIEW

**Comment by matentzn** [comment]
Test the wbbt.obo to see where this gets you with your ingest errors! Let me know if there are any more.

**Comment by raymond91125** [comment]
There are unionof (union_of) relations got filtered out from the simple file. They should be retained.
Just a note, unionof in WBbt is the same as owl2 DisjointUnion <https://www.w3.org/TR/owl2-new-features/>.

**Comment by matentzn** [comment]
@raymond91125 I will look into this! Out of curiosity, what are you using union_of for?

**Comment by raymond91125** [comment]
some worm cells can come from one of two possible lineages (ancestry). thus we need some sort of XOR relationship.

**Comment by matentzn** [comment]
can this wait till Friday? I think I need to have some discussions about doing this properly with my boss, who is on travelling at the moment..

**Comment by raymond91125** [comment]
Sure thing. Just note that I should really fix this type of relations. In Protege, presently, they are represented as (e.g.)
'P1.aaaa nucleus' or 'W.aaa nucleus'
But they should be:
('P1.aaaa nucleus' or 'W.aaa nucleus') and not ('P1.aaaa nucleus' and 'W.aaa nucleus')
I don't think either of these can be reasoned in Protege, though. HermiT seems to go on forever.

**Comment by cmungall** [comment]
Contact me so I don't forget about this. I don't think your use case/biology maps onto OWL axioms in exactly the way it may seem on the surface.

**Comment by matentzn** [comment]
We already took the discussion offline. we are getting rid of the logical axiom for now; see email thread.

**Comment by matentzn** [comment]
@raymond91125 Sorry for the back and forth here. After some recommendations offline by @cmungall I decided to leave your modelling as it was for now and redefine the OBO export of wbbt as follows: Take the full version of wbbt, remove all non-native (non WBbt) classes, remove redundant subsumptions and export to OBO. Please test wbbt.obo one last time here. I hope the typedefs in the end are not bothering you, else I will get rid of them in a second step.

**Comment by chris-grove** [comment]
@raymond91125 
Have you had a chance to look at this?

**Pull request merged**
