### PR TITLE
Remove 'Cell' as superclass of 'germ line' Sep 30 2019

### PR DESCRIPTION
**Pull request by chris-grove**
The anatomy term 'germ line' should not be a subclass of 'Cell', so removing 'Cell' as a superclass of 'germ line'

### CODE REVIEW

**Comment by chris-grove** [comment]
The germ line isn't a type of cell, it is a set of cells that are, or give rise to, the gametes. From WormAtlas, germline is defined as:
"The lineage that gives rise to all germ cells in an animal, that is the spermatozoa, oocytes and their precursors, through repeated cell divisions stemming from a single founder cell, the P4 blastomere."
so, according to WormAtlas it is a lineage of cells, not a cell itself, which is much more in line with my understanding. Also, from Wikipedia, germline is defined as:
"the germline in a multicellular organism is the population of its bodily cells that are so differentiated or segregated that in the usual processes of reproduction they may pass on their genetic material to the progeny."
so a population or set of cells, but again, not a cell itself.
Do you have a source of definition that defines "germline" as a cell?

**Comment by chris-grove** [comment]
Actually, I should have referenced the WBbt definition first:
"cell line which early in development becomes differentiated from the remaining somatic cell line, and alone has the potential to undergo meiosis and form gametes."
Also, defined not as a cell but a cell line

**Comment by raymond91125** [comment]
I think "a line of cells" is a cell type, just as AB lineage cell is a cell type.

**Comment by chris-grove** [comment]
No, a "cell line" ≠ "cell"
A cell line may have members that are cells that are of one or more cell types, but the cell line itself is not a cell. The cell line, I think, should be considered a tissue or a lineage or both, but not a cell. We would have to ask the question: "What is an example of an individual of this class?" An individual germ line in C. elegans would be the set of all individual cells (across the life span) that are germ cells or germ cell precursors. An individual C. elegans germ line would never be an individual cell, only ever a set of cells, and a set of cells is not the same as an individual cell.

**Comment by raymond91125** [comment]
Would it make sense to you if we rename germline to "germline cell" and have it as a subtype of "cell"? When we refer to a cell type, we mean any of its members, which could be all. In anatomy ontology, we don't have terms that are necessarily "all" but not any of its subsets.

**Comment by chris-grove** [comment]
No, we shouldn't rename "germline" to "germline cell" because

1) We already have "germ cell" which would be, as far as I can tell, exactly equivalent to "germline cell". WormAtlas defines "germ cell" as:

"Any member cell of the male or female germline, including sperm, oocytes, and their precursors. In the nematode gonad, the germ line proliferates from one primordial germ cell (PGC). Immature germ cells are not completely cellularized; instead they each maintain a syncytial linkage via the rachis, yet also retain their individual plasma membrane borders. Individual “cells” seem to act independently within this syncytium, therefore each connecting element, containing one nucleus, a few cytoplasmic organelles and a bounding plasma membrane is considered a separate germ cell."

2) A "germline" is still an anatomical entity that people refer to and therefore we should keep it as a term in the ontology, but it shouldn't be defined as a cell, or even a cell type; the C. elegans germline is the set of all germ cells in an individual worm, it is not a cell or a cell type itself.

"In anatomy ontology, we don't have terms that are necessarily "all" but not any of its subsets."

By "subsets" I think you are referring to part-of descendants here, as germ cells are part of the germline, but not subsets as in subclasses because germ cells are not a subclass of (a subtype of) germline. Again, a set of entities is not the same thing as an individual entity, nor is it a superclass of said entity. For example, a human being is not a subclass/subtype of population of human beings, a human being is only part-of a population of human beings. Part-of descendants are distinct from is-a/subclass descendants.

**Comment by raymond91125** [comment]
I guess there are two usage of germline. One general, that refers to germ cells <e.g. https://www.genome.gov/genetics-glossary/germ-line>, and one specific, that refers to the tissue in the worm where germ cells are collectively found (WormAtlas). In the second usage, germ cells are not always part of a germline, though, e.g. sperm transferred during sex .
So there is the 'sex' (in contrast to somatic) cells (which I think is a cell type that includes both immature and mature germ cells) and then there is something in which the germ cells are physically bound together (part of a gonad). I think our current treatment is a mixture of both meanings which is, I agree, a problem.

**Comment by chris-grove** [comment]
I actually don't think there are two uses of the term. The genome.gov link says:

"The germ line is the sex cells [sic]"

which I interpret to mean the set of all sex (germ) cells in the organism. I'm pretty sure that is the intended meaning which is consistent with what I've been saying, and is still consistent with the WormAtlas definition. 

OK, I agree that technically speaking, sperm that has been transferred to a mate is no longer part of the germline as a contiguous physical entity, but it could still be considered part of the germline even if it has been physically separated. If we really want to get pedantic, we can create terms/classes and definitions that would accommodate sperm that has already left the male's body, but I don't think it's worth it at this point.

So, I don't think we have a mixture of meanings problem. As I proposed, I think we just need to:

1) Remove "germ line" as a subclass of "Cell" (but leave it as a subclass of "Tissue")
2) Replace "germ line" as a superclass of "germ cell" with "Cell" as the new superclass

**Comment by chris-grove** [comment]
@raymond91125 
OK, I've made the last change that we discussed on the call. I've removed "germline precursor cell" as a subclass of "germ line" and made it a direct subclass of "Cell" instead.

**Pull request merged**
